CREATE TABLE [dbo].[INFOS] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [SURNAME]     VARCHAR (MAX) NULL,
    [FIRSTNAME]   VARCHAR (MAX) NULL,
    [MIDDLENAME]  VARCHAR (MAX) NULL,
    [SUFFIX]      VARCHAR (MAX) NULL,
    [HOUSEHOLD]   VARCHAR (MAX) NULL,
    [PUROK]       INT           NULL,
    [ADDRESS]     VARCHAR (MAX) NULL,
    [BIRTHDATE]   DATE          NULL,
    [SEX]         VARCHAR (MAX) NULL,
    [SIBLING]     VARCHAR (MAX) NULL,
    [CIVILSTATUS] VARCHAR (MAX) NULL,
    [CONTACT]     VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

